package com.kevin.drools.demo.basic.stateless

global org.slf4j.Logger log;

rule "Is of valid age"
when
    Applicant(age >= 18)
    $a : Application()
then
    log.info("Executing rule: [" + drools.getRule().getName() + "]");
    $a.setValid(true);
end;

rule "Application was made this year"
when
    $a : Application(dateApplied > "01-jan-2014")
then
    $a.setValid(false);
end;